/*
 * This Hyperlambda snippet demonstrates the use of `finally`.
 * The `finally` block executes regardless of whether an exception is caught.
 * Expected behavior: `.throws` should always be `true` after execution.
 */

.throws:bool:false
try
   throw:foo
.catch
.finally
   set-value:x:@.throws
      .:bool:true
