/*
 * This Hyperlambda snippet demonstrates an uncaught exception.
 * Since there is no `catch` block, the exception propagates and results in a `HyperlambdaException`.
 * Expected behavior: The execution will fail with a `HyperlambdaException`.
 */

try
   throw:foo
